<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>es.cesguiro</groupId>
    <artifactId>daw-framework</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <org.codehaus.mojo.exec-maven-plugin.version>3.6.3</org.codehaus.mojo.exec-maven-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <org.apache.tomcat.version>11.0.25</org.apache.tomcat.version>
        <org.slf4j.version>2.0.18</org.slf4j.version>
        <ch.qos.logback.version>1.6.3</ch.qos.logback.version>
    </properties>
    <dependencies>
    <!-- Tomcat embebido, incluye Coyote, Catalina y JULI -->
    <!-- Tomcat Catalina: contenedor de servlets -->
    <!-- Tomcat Coyote: conector HTTP. Escucha las solicitudes HTTP -->
    <!-- Tomcat JULI: redirige el logging de java.util.logging a SLF4J -->
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <version>${org.apache.tomcat.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- Redirige el logging de java.util.logging a SLF4J -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jul-to-slf4j</artifactId>
            <version>${org.slf4j.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- Logback: implementación de SLF4J -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${ch.qos.logback.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${org.codehaus.mojo.exec-maven-plugin.version}</version>
                <configuration>
                    <mainClass>es.cesguiro.daw.framework.App</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>